package com.knu.ddip.ddipevent.domain;

public enum MessageCode {
    // APPROVE
    THANKS_A_LOT,
    GREAT_SENSE,

    // REQUEST_REVISION
    BLURRED,
    TOO_FAR,
    WRONG_SUBJECT,

    // REPORT_SITUATION
    GONE_ALREADY,
    SOLD_OUT,
    PLACE_CLOSED,
    ACCESS_DENIED,
    TOO_CROWDED_TO_SHOOT,
    LONG_QUEUE,

    // GIVE_UP_BY_RESPONDER
    PERSONAL_REASON,
    TOO_LONG_DISTANCE,
    REQUEST_UNCLEAR;
}
